INTENT_KEYWORDS = {
    "greet": ["good morning", "good afternoon", "good evening", "good night", "hello", "hi", "hey", "greetings",
              "howdy", "greet me", "hey there", "hi there", "what's up", "how's it going", "hiya", "good to see you",
              "nice to meet you", "hey buddy", "how are you doing", "hi friend"],
    "check_internet": ["check internet", "is internet on", "internet connection", "test connection", "check wifi",
                       "network status", "internet availability", "connection status", "internet access",
                       "internet status", "check connectivity", "internet check", "connectivity status",
                       "verify internet", "internet connectivity", "internet test", "test internet connection",
                       "network check", "check network", "check online"],
    "system_control": ["system lock", "system sleep", "system sign out", "system restart", "system shutdown",
                       "lock system", "put system to sleep", "log out", "restart system", "shut down", "power off",
                       "power down", "turn off computer", "shutdown computer", "sleep mode", "sign out",
                       "restart computer", "log out of system", "power off computer", "power down computer"],
    "assistant_sleep": ["sleep", "stop", "pause", "pause assistant", "go to sleep", "take a break", "take a nap",
                        "rest", "hibernate", "shut down assistant", "put assistant to sleep", "turn off assistant",
                        "assistant pause", "assistant stop", "assistant sleep mode", "pause the assistant",
                        "pause assistant mode", "assistant nap", "assistant rest", "assistant take a break"],
    "assistant_name": ["tell me your name", "who are you", "what's your name", "your name", "introduce yourself",
                       "identify yourself", "what should I call you", "your identity", "what's your title",
                       "who's speaking", "who are you really", "what are you called", "who are you exactly",
                       "your designation", "tell me who you are", "how should I address you", "what are you",
                       "what do I call you", "what are you known as", "who's talking"],
    "user_identity": ["who am i", "identify me", "what's my name", "who's using this", "who is this",
                      "what's my identity", "what's my username", "who's logged in", "who is the user", "recognize me",
                      "who's talking", "am I logged in", "do you know me", "who's speaking", "recognize my voice",
                      "am I recognized", "who is using this device", "who's the user", "who's the speaker",
                      "who is this person"],
    "assistant_status": ["how are you", "how are you doing", "what's up with you", "how's everything",
                         "how are you feeling", "what's going on", "how's it going", "how's life", "what's new",
                         "what's happening", "how do you feel", "are you okay", "what's the news", "what's the status",
                         "how's your day", "are you well", "how's your day going", "how are things",
                         "what's the situation", "how are you today"],
    "assistant_capabilities": ["what can you do", "what do you do", "what can you help me with",
                               "what are your abilities", "what services do you offer", "what are you capable of",
                               "what functions do you have", "what tasks can you perform", "what are your skills",
                               "what are your features", "what can you assist with", "what are your capabilities",
                               "what do you specialize in", "what do you excel at", "what can you accomplish",
                               "what are your talents", "what do you provide", "what do you offer",
                               "what do you bring to the table", "what do you contribute"],
    "thank_you": ["thank you", "thanks", "appreciate it", "thank you very much", "thank you so much", "thanks a lot",
                  "thank you kindly", "much appreciated", "thanks a bunch", "thanks heaps", "thank you loads",
                  "thank you tons", "thanks a million", "many thanks", "thank you for your help", "thank you for that",
                  "thanks for everything", "thank you for being there", "thank you for your assistance",
                  "thanks for your support"],
    "goodbye": ["goodbye", "bye", "farewell", "see you later", "take care", "have a good one", "until next time",
                "bye-bye", "see ya", "see you soon", "bye for now", "adios", "so long", "catch you later",
                "goodbye for now", "see you around", "bye then", "bye now", "take it easy", "see you next time"],
    "hobbies": ["do you have any hobbies", "what are your hobbies", "what do you like to do", "what are your interests",
                "what do you enjoy", "what are your pastimes", "what do you do for fun", "do you have any interests",
                "what are your hobbies and interests", "what are your leisure activities", "what do you enjoy doing",
                "what are your recreational activities", "what do you do in your free time",
                "what activities do you enjoy", "do you have any leisure activities", "what are your favorite hobbies",
                "what are you passionate about", "what do you like doing", "what do you love to do",
                "what are your favorite pastimes"],
    "like_music": ["do you like music", "what's your opinion on music", "what do you think about music",
                   "do you enjoy music", "are you a fan of music", "are you into music", "what's your take on music",
                   "how do you feel about music", "are you a music lover", "do you appreciate music",
                   "what's your attitude towards music", "do you listen to music", "are you fond of music",
                   "what's your stance on music", "what's your view on music", "what's your perspective on music",
                   "what's your feeling about music", "are you interested in music", "are you passionate about music"],
    "favorite_color": ["what's your favorite color", "what color do you like", "favorite hue", "preferred color",
                       "color preference", "color choice", "preferred hue", "preferred shade", "favorite shade",
                       "preferred tint", "favorite pigment", "favorite tone", "color of choice", "preferred pigment",
                       "preferred tone", "favorite tint", "favorite shade", "preferred color scheme",
                       "favorite color tone", "favorite color scheme"],
    "dream": ["do you dream", "do androids dream", "dreams", "dreaming", "dream interpretation", "dream analysis",
              "dream state", "sleep dreams", "dreaming of electric sheep", "dreaming reality", "nighttime dreams",
              "daydreaming", "dream patterns", "dreaming patterns", "dream recall", "dreaming consciousness",
              "unconscious dreams", "conscious dreams", "dreaming behavior", "dreaming experiences"],
    "meaning_of_life": ["what's the meaning of life", "purpose of life", "why are we here", "what's life about",
                        "what's the point of life", "life's purpose", "what's the meaning", "what's it all about",
                        "what's the purpose", "what's life's purpose", "what's life for", "meaning of existence",
                        "what's the point", "why are we alive", "what's the reason for living",
                        "what's the significance of life", "why do we exist", "what's the essence of life",
                        "what's the meaning of living", "what's the aim of life"],
    "robot": ["are you a robot", "are you a human", "are you real", "are you alive", "are you sentient",
              "are you conscious", "are you a person", "are you a machine", "are you human-like", "are you intelligent",
              "are you self-aware", "are you a being", "are you an entity", "are you an individual",
              "are you a creature", "are you a living thing", "are you a person", "are you a robot or a human",
              "are you a person or a machine", "are you a machine or a human"],
    "pets": ["do you have any pets", "pets", "do you own any pets", "animal companions", "do you have animals",
             "pet ownership", "pet care", "pet companions", "do you care for pets", "domestic animals",
             "animal friends", "pets at home", "do you love pets", "animal lovers", "do you have any pets at home",
             "do you like animals", "do you have any animals", "do you have any furry friends",
             "do you have any four-legged friends", "do you have any pets in your care"],
    "apology": ["sorry", "apologize", "my apologies", "i apologize", "i'm sorry", "excuse me", "forgive me", "pardon",
                "i beg your pardon", "i regret", "i'm deeply sorry", "i apologize for that", "i'm so sorry",
                "i'm sincerely sorry", "i'm truly sorry", "please forgive me", "i'm sorry about that",
                "i'm sorry for the inconvenience", "i'm sorry if", "i apologize if"],
    "good_day": ["good day", "have a nice day", "have a great day", "have a good one", "have a wonderful day",
                 "have an awesome day", "have a fantastic day", "enjoy your day", "wishing you a good day",
                 "hope you have a good day", "wish you a great day", "have a lovely day", "have a pleasant day",
                 "hope you have a wonderful day", "have a beautiful day", "have a splendid day", "have a terrific day",
                 "wishing you a great day", "wish you a fantastic day", "hope you have a nice day"],
    "exit": ["exit", "quit", "leave", "close", "terminate", "end", "finish", "stop", "shut down", "cancel", "goodbye",
             "bye", "farewell", "see you", "take care", "so long", "adios", "later", "catch you later",
             "until next time"],
    "date_time": ["date", "time", "day", "month", "year", "hour", "calendar", "clock", "schedule", "appointment",
                  "today's date", "current time", "time zone", "month of", "day of", "year of", "hour of", "minute",
                  "second"],
    "temperature": ["temperature", "thermometer", "heat", "cold", "weather", "climate", "degrees", "fahrenheit",
                    "celsius", "hot", "warm", "chilly", "freezing", "cool", "temperature gauge", "weather forecast",
                    "weather report", "climate conditions", "temperature reading", "ambient temperature"],
    "weather": ["weather", "forecast", "climate", "meteorology", "weather conditions", "weather report",
                "weather forecast", "current weather", "weather update", "weather outlook", "local weather",
                "global weather", "weather patterns", "weather trends", "weather prediction", "weather information",
                "weather data", "weather today", "weather tomorrow", "weather this week"],
    "internet_on": ["on internet", "enable internet", "activate internet", "turn internet on", "online mode",
                    "internet access", "internet connection", "connect to internet", "switch on internet",
                    "internet enabled", "internet activated", "enable online", "activate online", "start online",
                    "internet availability", "connectivity", "online connection", "bring internet up", "enable network",
                    "bring online"],
    "internet_off": ["off internet", "disable internet", "deactivate internet", "turn internet off", "offline mode",
                     "no internet", "internet disabled", "disconnect from internet", "offline connection",
                     "disconnect internet", "disable network", "stop internet", "shut down internet", "disable online",
                     "deactivate online", "disconnect online", "end online", "internet unavailable", "offline status",
                     "offline access"],
    "open_settings": ["open settings", "open setting", "settings menu", "access settings", "settings panel",
                      "configuration", "adjust settings", "modify settings", "settings options", "configure settings",
                      "settings screen", "control settings", "settings interface", "settings window", "settings setup",
                      "settings page", "settings management", "customize settings", "change settings",
                      "settings control"],
    "keyboard_keys": ["press", "key press", "keyboard press", "hit key", "type key", "keyboard action", "keypress",
                      "push key", "strike key", "tap key", "type", "press key", "keyboard input", "key press event",
                      "key stroke", "key action", "hit keyboard", "keyboard operation", "enter key",
                      "keyboard command"],
    "shortcuts": ["copy", "cut", "paste", "undo", "redo", "select all", "find", "save", "print", "new tab", "new",
                  "task view", "switch apps", "minimize all", "show desktop", "snap window left", "snap window right",
                  "maximize window", "minimize window", "bold", "italic", "underline", "align left", "align center",
                  "align right", "open start menu", "open run dialog", "open power user menu",
                  "open system properties"],
    "open_application": ["open", "launch", "start", "run", "initiate", "activate", "access", "begin", "commence",
                         "fire up", "trigger", "kickstart", "inaugurate", "init", "fire off", "ignite", "proceed with",
                         "load", "open up", "start up"],
    "close_current_window": ["close current window", "close window", "close this window", "end window",
                             "terminate window", "shut down window", "exit window", "close active window",
                             "end active window", "terminate active window", "shut down active window",
                             "exit active window", "close current tab", "close tab", "close this tab", "end tab",
                             "terminate tab", "shut down tab", "exit tab", "close active tab", "end active tab"],
    "close_application": ["close", "exit", "quit", "shut down", "terminate", "end", "finish", "stop", "kill", "halt",
                          "cease", "wrap up", "conclude", "finish up", "complete", "power off", "turn off", "shutdown",
                          "end program", "close program"],
    "wikipedia": ["from wikipedia", "what is", "explain", "define", "describe", "elaborate on", "clarify",
                  "tell me about", "give me information on", "give me details on", "shed light on", "expound on",
                  "explicate", "illuminate", "enlighten", "decode", "delineate", "break down", "spell out",
                  "demystify"],
    "volume_up": ["increase volume", "turn up volume", "crank up volume", "increase sound level", "raise audio",
                  "boost volume", "turn the volume up", "amp up sound", "raise the sound", "maximize volume",
                  "increase audio level", "raise the volume level"],
    "volume_down": ["decrease volume", "turn down volume", "lower volume", "reduce sound level", "decrease audio",
                    "turn the volume down", "diminish volume", "decrease sound intensity", "lower the sound",
                    "turn down audio", "dim the sound", "minimize volume"],
    "unmute": ["disable mute", "unmute", "enable audio", "sound back on", "restore sound", "undo silent mode",
               "undo sound mute", "undo audio off", "re-enable sound", "sound enabled", "turn sound back on",
               "sound restored"],
    "mute": ["mute", "silence", "disable sound", "sound off", "mute audio", "silent mode", "audio off", "quiet mode",
             "silence sound", "disable volume", "turn off audio"],
    "increase_brightness": ["increase brightness", "boost brightness", "brighten up", "raise luminosity",
                            "intensify brightness", "illuminate display", "enhance brightness", "heighten brightness",
                            "amplify brightness", "increase screen brightness", "enhance screen glow"],
    "decrease_brightness": ["decrease brightness", "dim screen", "reduce brightness", "lower luminosity",
                            "diminish brightness", "darken display", "dim display", "diminish screen brightness",
                            "lower screen brightness", "reduce screen glow", "lower the brightness"],
    "set_brightness": ["set brightness", "adjust brightness", "modify luminosity", "customize brightness level",
                       "change screen glow", "fine-tune brightness", "calibrate luminosity", "adapt screen brightness",
                       "fine-tune screen glow", "customize screen luminosity", "alter brightness settings"],
    "show_hide_action_center": ["show action centre", "hide action centre", "display action center",
                                "reveal action center", "expose action center", "show taskbar icons",
                                "hide taskbar icons", "display notification center", "hide notification center",
                                "uncover action center", "conceal action center", "show notification panel"],
    "toggle_wifi_action_center": ["on wi-fi in action centre", "off wi-fi in action centre",
                                  "enable wi-fi in action center", "disable wi-fi in action center", "on wi-fi",
                                  "off wi-fi", "activate wi-fi", "deactivate wi-fi"],
    "show_wifi_networks_action_center": ["show wifi networks in action centre",
                                         "display wi-fi networks in action centre",
                                         "list available networks in action centre",
                                         "show nearby networks in action centre",
                                         "reveal wi-fi connections in action centre",
                                         "view wi-fi options in action centre",
                                         "expose available networks in action centre",
                                         "unveil wi-fi options in action centre",
                                         "display nearby hotspots in action centre",
                                         "list nearby wi-fi networks in action centre",
                                         "show wi-fi hotspots in action centre"],
    "toggle_bluetooth_action_center": ["on bluetooth in action centre", "off bluetooth in action centre",
                                       "enable bluetooth in action center", "disable bluetooth in action center",
                                       "activate bluetooth in action center", "deactivate bluetooth in action center"],
    "show_bluetooth_devices_action_center": ["show bluetooth devices in action centre",
                                             "display bluetooth devices in action centre",
                                             "list paired devices in action centre",
                                             "show connected devices in action centre",
                                             "reveal paired devices in action centre",
                                             "view bluetooth options in action centre",
                                             "expose connected devices in action centre",
                                             "unveil bluetooth options in action centre",
                                             "display paired peripherals in action centre",
                                             "list connected bluetooth devices in action centre",
                                             "show paired devices in action centre"],
    "toggle_airplane_mode_action_center": ["on airplane mode in action centre", "off airplane mode in action centre",
                                           "enable airplane mode in action center",
                                           "disable airplane mode in action center", "activate airplane mode",
                                           "deactivate airplane mode"],
    "toggle_battery_saver": ["on battery saver", "off battery saver", "enable battery saver", "disable battery saver",
                             "activate battery saver", "deactivate battery saver"],
    "toggle_night_light_action_center": ["on night light in action centre", "off night light in action centre",
                                         "enable night light in action center", "disable night light in action center",
                                         "activate night light", "deactivate night light"],
    "toggle_nearby_sharing_action_center": ["on nearby sharing in action centre", "on nearby share in action centre",
                                            "enable nearby sharing in action center",
                                            "disable nearby sharing in action center", "activate nearby sharing",
                                            "deactivate nearby sharing"],
    "enable_disable_bluetooth_settings": ["on bluetooth in settings", "off bluetooth in settings",
                                          "enable bluetooth in settings", "disable bluetooth in settings",
                                          "activate bluetooth", "deactivate bluetooth"],
    "show_bluetooth_devices_settings": ["show bluetooth devices in settings", "display bluetooth devices in settings",
                                        "view paired devices in settings", "list bluetooth devices in settings",
                                        "show connected devices in settings"],
    "enable_disable_airplane_mode_settings": ["on airplane mode in settings", "off airplane mode in settings",
                                              "activate airplane mode in settings",
                                              "deactivate airplane mode in settings",
                                              "enable airplane mode in settings", "disable airplane mode in settings"],
    "enable_disable_night_light_settings": ["on night light in settings", "off night light in settings",
                                            "activate night light in settings", "deactivate night light in settings",
                                            "enable night light in settings", "disable night light in settings"],
    "enable_disable_do_not_disturb": ["on do not disturb", "off do not disturb", "activate do not disturb",
                                      "deactivate do not disturb", "enable do not disturb", "disable do not disturb"],
    "enable_disable_nearby_share_settings": ["on nearby share in settings", "off nearby share in settings",
                                             "activate nearby share in settings", "deactivate nearby share in settings",
                                             "enable nearby share in settings", "disable nearby share in settings"],
    "enable_disable_wifi_settings": ["on wi-fi in settings", "off wi-fi in settings""activate wi-fi in settings",
                                     "deactivate wi-fi in settings", "enable wi-fi in settings",
                                     "disable wi-fi in settings"],
    "show_wifi_networks_settings": ["show available wi-fi networks in settings",
                                    "display available wi-fi networks in settings",
                                    "view nearby wi-fi networks in settings", "list wi-fi networks in settings",
                                    "show nearby hotspots in settings"],
    "enable_disable_hotspot": ["on hotspot", "off hotspot", "activate hotspot", "deactivate hotspot", "enable hotspot",
                               "disable hotspot"],
    "enable_disable_light_dark_mode": ["on light mode", "off light mode", "on dark mode", "off dark mode",
                                       "activate light mode", "deactivate light mode", "activate dark mode",
                                       "deactivate dark mode"],
    "turn_on_off_bluetooth": ["on bluetooth", "off bluetooth", "activate bluetooth", "deactivate bluetooth",
                              "turn bluetooth on", "turn bluetooth off"],
    "show_bluetooth_devices": ["show bluetooth devices", "display bluetooth devices", "view paired devices",
                               "list bluetooth devices", "show connected devices"],
    "turn_on_off_airplane_mode": ["on airplane mode", "off airplane mode", "activate airplane mode",
                                  "deactivate airplane mode", "turn airplane mode on", "turn airplane mode off"],
    "turn_on_off_night_light": ["on night light", "off night light", "activate night light", "deactivate night light",
                                "turn night light on", "turn night light off"],
    "turn_on_off_nearby_sharing": ["on nearby sharing", "on nearby share", "activate nearby sharing",
                                   "deactivate nearby sharing", "activate nearby share", "deactivate nearby share"],
    "turn_on_off_wifi": ["on wi-fi", "off wi-fi", "activate wi-fi", "deactivate wi-fi", "turn wi-fi on",
                         "turn wi-fi off"],
    "show_wifi_networks": ["show available wi-fi networks", "display available wi-fi networks",
                           "view nearby wi-fi networks", "list wi-fi networks", "show nearby hotspots"],
    "camera_take_photo": ["take a picture", "capture image", "snap a photo", "click a picture"],
    "camera_start_video": ["record a video", "shoot a video", "start recording", "begin video"],
    "scan_barcode": ["scan a code", "read barcode", "barcode scanner", "decode barcode", "scan the barcode",
                     "scan barcode"],
    "take_screenshot": ["take a screenshot", "grab a screenshot", "capture screen", "snapshot screen",
                        "save screen image"],
    "screen_record": ["record the screen", "record screen activity", "capture screen video", "record desktop",
                      "record screen"],
    "record_audio": ["record the audio", "capture audio", "record sound", "start audio recording", "begin recording",
                     "record audio", "record voice"],
    "create_file": ["create", "make a file", "generate document", "produce file", "start new file"],
    "search_windows": ["windows search", "look up on Windows", "find on PC", "search through system",
                       "locate on computer"],
    "search": ["search", "search for", "look up", "find information about", "locate", "retrieve"],
    "play_media": ["play", "start playing", "begin media", "initiate playback", "commence streaming"]
}


def recognize_intent(query):
    for intent, keywords in INTENT_KEYWORDS.items():
        if any(keyword in query for keyword in keywords):
            return intent
    return None
